name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        shell: julia --color=yes {0}
        run: |
          using CompatHelper
          using Pkg
          registries = [
              Pkg.RegistrySpec(
                  name = "General",
                  uuid = "23338594-aafe-5451-b93e-139f81909106",
                  url = "https://github.com/JuliaRegistries/General.git",
              ),
              Pkg.RegistrySpec(
                  name = "ITensorRegistry",
                  uuid = "c4d53e37-7e0e-4be9-ba6f-c27e01f48020",
                  url = "https://github.com/ITensor/ITensorRegistry.git",
              ),
          ]
          CompatHelper.main(; registries)
